// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaIVFjurMllxZ6IHGYhIc6Za_7hctLLRg',
    appId: '1:921035896750:web:8fe2af8b0e78584eb67a3f',
    messagingSenderId: '921035896750',
    projectId: 'bloodconnect-e1ceb',
    authDomain: 'bloodconnect-e1ceb.firebaseapp.com',
    storageBucket: 'bloodconnect-e1ceb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-6KI0nfpH1IB_IGJUXKgXdXYsL58sscQ',
    appId: '1:921035896750:android:e3312a525ce2e57eb67a3f',
    messagingSenderId: '921035896750',
    projectId: 'bloodconnect-e1ceb',
    storageBucket: 'bloodconnect-e1ceb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnsem3yhwFenijGO2FlWA4G3ny50qSDf4',
    appId: '1:921035896750:ios:9a445c3f1cf7ac5db67a3f',
    messagingSenderId: '921035896750',
    projectId: 'bloodconnect-e1ceb',
    storageBucket: 'bloodconnect-e1ceb.firebasestorage.app',
    androidClientId: '921035896750-nsg1iu3o6l2mphh149p2nudqutf5daof.apps.googleusercontent.com',
    iosClientId: '921035896750-6vbs6fb01pggrlhcmk2vt5qsf2d0fbo3.apps.googleusercontent.com',
    iosBundleId: 'com.example.bloodconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnsem3yhwFenijGO2FlWA4G3ny50qSDf4',
    appId: '1:921035896750:ios:9a445c3f1cf7ac5db67a3f',
    messagingSenderId: '921035896750',
    projectId: 'bloodconnect-e1ceb',
    storageBucket: 'bloodconnect-e1ceb.firebasestorage.app',
    androidClientId: '921035896750-nsg1iu3o6l2mphh149p2nudqutf5daof.apps.googleusercontent.com',
    iosClientId: '921035896750-6vbs6fb01pggrlhcmk2vt5qsf2d0fbo3.apps.googleusercontent.com',
    iosBundleId: 'com.example.bloodconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaIVFjurMllxZ6IHGYhIc6Za_7hctLLRg',
    appId: '1:921035896750:web:8502c5d1af5f0d24b67a3f',
    messagingSenderId: '921035896750',
    projectId: 'bloodconnect-e1ceb',
    authDomain: 'bloodconnect-e1ceb.firebaseapp.com',
    storageBucket: 'bloodconnect-e1ceb.firebasestorage.app',
  );
}
